let tmp = [
    "Đi dạo, ngắm cảnh",
    "Ẩm thực, nghỉ ngơi",
    "Đồ uống, thư giãn",
    "Văn hóa, lịch sử, nghệ thuật",
    "Văn hóa tôn giáo, tâm linh",
    "Trung tâm thương mại",
    "Triển lãm, nghệ thuật",
    "Trải nghiệm đa dạng, văn hóa, ẩm thực,...",
    "Vườn hoa, cảnh đẹp",
    "Công viên nước, vui chơi giải trí",
    "Thể thao, chèo thuyền",
    "Ẩm thực chay",
    "Tàu điện, chụp ảnh",
    "Công viên, văn hóa, lịch sử",
    "Công viên, đi dạo, ngắm cảnh",
    "Biểu diễn nghệ thuật dân gian",
    "Thủy cung, vui chơi giải trí",
    "Tổ hợp thể thao, đi dạo ngắm cảnh",
    "Vui chơi, giải trí",
    "Công viên, sở thú, vui chơi, giải trí",
]